steps:
  mavenBuild:
    verbose: false
    verify: true
    flatten: true
    # https://www.project-piper.io/steps/mavenBuild/#dockerimage
    dockerImage: ""

  detectExecuteScan:
    projectName: "com.sap.cds.feature.ord"
    groups:
      - "CDSJAVA-OPEN-SOURCE"
    serverUrl: "https://sap.blackducksoftware.com/"
    mavenExcludedScopes: [ "provided", "test" ]
    failOn: [ "BLOCKER", "CRITICAL", "MAJOR" ]
    versioningModel: "major-minor"
    detectTools: [ "DETECTOR", "BINARY_SCAN" ]
    installArtifacts: true
    owner: "cap-java"
    repository: "cds-feature-ord"
    verbose: true
    scanProperties:
      - --detect.included.detector.types=MAVEN
      - --detect.excluded.directories='**/node_modules,**/*test*,**/localrepo,**/target/site,**/*-site.jar'
      - --detect.maven.build.command='-pl com.sap.cds:cds-feature-ord'
    # https://www.project-piper.io/steps/detectExecuteScan/#dockerimage
    dockerImage: ""

  sonarExecuteScan:
    serverUrl: https://sonar.tools.sap
    projectKey: cds-feature-ord
    # https://www.project-piper.io/steps/sonarExecuteScan/#dockerimage
    dockerImage: ""
    options:
      - sonar.qualitygate.wait=true
      - sonar.java.source=21
      - sonar.sources=cds-feature-ord/src/main/java
      - sonar.exclusions=**/node_modules/**,**/target/**
      - sonar.coverage.jacoco.xmlReportPaths=cds-feature-ord/target/site/jacoco/jacoco.xml