name: CI - MAIN

env:
  JAVA_VERSION: '21'
  MAVEN_VERSION: "3.9.16"

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  blackduck:
    name: Blackduck Scan
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6

      - name: Scan With Black Duck
        uses: cap-java/.github/actions/scan-with-blackduck@main
        with:
          scan_mode: FULL
          included-modules: cds-feature-ord
          project-name: com.sap.cds.feature.ord
          excluded-dirs: '**/*test*,**/target/site'
          java-version: ${{ env.JAVA_VERSION }}
          maven-version: ${{ env.MAVEN_VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          blackduck_token: ${{ secrets.BLACK_DUCK_TOKEN }}

  build-and-test:
    uses: ./.github/workflows/pipeline.yml
    permissions:
      contents: read
      security-events: write
      actions: read
      packages: read
    secrets: inherit